select
  p.id as patient_id,
  rp.id as participation_id,
  rs.id as study_id,
  rp.document ->> 'study_number' as heroic_patient_number,
  hc.code as hospital_centre_code,
  p.nhs_number,
  p.family_name,
  p.given_name,
  p.title,
  p.born_on,
  EXTRACT(year FROM born_on) :: int as year_of_birth,
  EXTRACT(year FROM age(current_date, born_on)) :: int as age,
  p.sex,
  rp.joined_on,
  rp.left_on,
  rp.document -> 'withdrawal' ->> 'status' as withdrawal_status,
  rp.document -> 'withdrawal' ->> 'partial_withdrawal_date' as partial_withdrawal_date,
  rp.document -> 'withdrawal' ->> 'complete_withdrawal_date' as complete_withdrawal_date,
  rp.document -> 'consent' ->> 'type' as consent_type,
  rp.document -> 'consent' ->> 'date' as consent_date,
  rp.document -> 'clinical_history' ->> 'diabetes_type' as diabetes_type,
  rp.document -> 'mri_antaros_0' ->> 'booked_for' as mri_antaros_0_booked_for,
  rp.document -> 'mri_antaros_0' ->> 'completed' as mri_antaros_0_completed,
  rp.document -> 'mri_antaros_2' ->> 'booked_for' as mri_antaros_2_booked_for,
  rp.document -> 'mri_antaros_2' ->> 'completed' as mri_antaros_2_completed,
  rp.document -> 'mri_antaros_5' ->> 'booked_for' as mri_antaros_5_booked_for,
  rp.document -> 'mri_antaros_5' ->> 'completed' as mri_antaros_5_completed,
  rp.document -> 'biopsy_histology' ->> 'biopsy_date' as biopsy_date,
  rp.document -> 'biopsy_histology' ->> 'no_biopsy' as no_biopsy,
  rp.document -> 'biopsy_histology' ->> 'no_biopsy_date' as no_biopsy_date,
  rp.document ->> 'blood_visit_0_date' as blood_visit_0_date,
  rp.document ->> 'blood_visit_1_date' as blood_visit_1_date,
  rp.document ->> 'blood_visit_2_date' as blood_visit_2_date,
  rp.document ->> 'blood_visit_3_date' as blood_visit_3_date,
  rp.document ->> 'blood_visit_4_date' as blood_visit_4_date,
  rp.document ->> 'blood_visit_5_date' as blood_visit_5_date,
  rp.document -> 'withdrawal' ->> 'status' <> ALL (ARRAY ['3_complete_withdrawal'::text, '4_inactive'::text]) as active,
  rp.document
from research_participations rp
inner join research_studies rs on rs.id = rp.study_id
inner join patients p on p.id = rp.patient_id
inner join hospital_centres hc on hc.id = p.hospital_centre_id
where rs.code = 'HEROIC' AND rs.deleted_at is NULL AND rp.deleted_at is NULL;
