version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/documentation"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
