version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      patch-updates:
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      minor-and-patch:
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/documentation"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
