require_relative "./system/seeds"
require_relative "./hospitals/seeds"
require_relative "./drugs/seeds"
require_relative "./patients/seeds"
require_relative "./admissions/seeds"
require_relative "./directory/seeds"
require_relative "./accesses/seeds"
require_relative "./clinical/seeds"
require_relative "./clinics/seeds"
require_relative "./events/seeds"
require_relative "./hd/seeds"
require_relative "./letters/seeds"
require_relative "./modalities/seeds"
require_relative "./pathology/seeds"
require_relative "./pd/seeds"
require_relative "./problems/seeds"
require_relative "./renal/seeds"
require_relative "./transplants/seeds"
require_relative "./medications/seeds"
require_relative "./worryboard/seeds"
require_relative "./snippets/seeds"

# This seed file must be run last
require_relative "./housekeeping"
