---
engines:
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 160
        javascript:
          mass_threshold: 100
  eslint:
    enabled: true
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  rubocop:
    enabled: true
  reek:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- bin/
- config/
- db/
- features/
- spec/
- vendor/
- tmp/
- coverage/
- lib/tasks/
- app/assets/javascripts/renalware/clockpicker.js
- app/assets/stylesheets/renalware/lib/_clockpicker.css
