version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/airslie/styleguide/master/rubocop.yml"
      path: "default.yml"
checks:
  similar-code:
    config:
      threshold: 160
plugins:
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  rubocop:
    enabled: true
    channel: rubocop-0-71
  reek:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
  eslint:
    enabled: true
# sass-lint:
#   enabled: true
#   csslint:
#     enabled: true
#   shellcheck:
#     enabled: true
#   eslint:
#     enabled: false
#   csslint:
#     enabled: true

exclude_patterns:
- bin/
- config/
- db/
- features/
- spec/
- vendor/
- tmp/
- coverage/
- lib/tasks/
- app/assets/javascripts/renalware/clockpicker.js
- app/assets/stylesheets/renalware/lib/_clockpicker.css
