# rubocop config vases loosely on
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
# but excluding standardrb for now as it removes spaces from hashes which is just plain ugly :)

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-factory_bot
  - rubocop-rspec_rails
  - rubocop-capybara

# Skip standard for now.
# inherit_gem:
#   standard: config/base.yml

inherit_from:
  - https://raw.githubusercontent.com/airslie/styleguide/main/rubocop.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  UseCache: true
  SuggestExtensions: true
  TargetRubyVersion: 3.4.4
  TargetRailsVersion: 7.1
  # Defining the Exclude or Include keys here overwrites the settings in styleguide/rubocop.yml
  # so we have to redefine the entire set.
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"
    - "bin/**/*"
    - "demo/bin/**/*"
    - "tmp/**/*"
    - "demo/tmp/**/*"
    - "vendor/bundle/**/*"
    - "config/initializers/devise.rb"
    - "features/support/env.xaction_view.rb"

Style/SafeNavigationChainLength:
  Enabled: true
  Max: 3

Rails/EnumHash:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: false

Rails/EnumSyntax:
  Enabled: true

Style/CommentAnnotation:
  Enabled: false

Rails/WhereRange:
  Enabled: true

Naming/PredicateName:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false
  CountBlocks: false

Rails/ToSWithArgument:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Style/AsciiComments:
  Enabled: true
  Exclude:
    - "app/models/renalware/feeds/hl7_message.rb"
    - "app/models/renalware/reporting/fetch_audit_json.rb"


Rails/ActionOrder:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true
  Exclude:
    - "spec/models/renalware/pathology/observation_requests_attributes_builder_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Max: 30

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/components/shared/**/*'

RSpec/ReceiveMessages:
  Enabled: true

RSpec/MetadataStyle:
  Enabled: true

RSpec/ExampleLength:
  Max: 40
  Exclude:
    - "spec/system/**/*"
RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10
  Exclude:
    - "spec/system/**/*"

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/models/renalware/letters/formats/fhir/**/resources/**/*

Layout/MultilineMethodCallIndentation:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - "lib/renalware/engine.rb"
Layout/LineLength:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"
    - "features/step_definitions/**/*"
    - "config/initializers/**/*"
    - "app/inputs/**.*"
    - "demo/db/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"
    - "features/**/*"
    - "db/**/*"
    - "demo/db/**/*"
    - app/models/renalware/letters/formats/fhir/**/resources/**/*
  Max: 25

Lint/RedundantSafeNavigation:
  Enabled: true
RSpec/DescribeClass:
  Enabled: true
RSpec/ImplicitSubject:
  Enabled: false
RSpec/DescribedClass:
  Enabled: true
Performance/RedundantBlockCall:
  Enabled: true
Style/NumericPredicate:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
Rails/DurationArithmetic:
  Enabled: true
Style/OpenStructUse:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false

# HL7 messages contain strings which seem to be escaped and aren't so its safest to disable this
# cop on all specs
Style/RedundantStringEscape:
  Enabled: true
  Exclude:
    - "spec/**/*"

# This is Ruby >=3.1 so we have to wait for Kings to upgrade
Naming/BlockForwarding:
  Enabled: true

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - "**/*_drop.rb"

Rails/UniqBeforePluck:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias

Lint/Debugger: # don't leave binding.pry
  Enabled: true
  Exclude: []

RSpec/Focus: # run ALL tests on CI
  Enabled: true
  Exclude: []

Rails/Output: # Don't leave puts-debugging
  Enabled: true
  Exclude: []

Rails/FindEach: # each could badly affect the performance, use find_each
  Enabled: true
  Exclude: []

Metrics/CollectionLiteralLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'demo/db/migrate/**/*'

Style/RedundantLineContinuation:
    Enabled: true
    Exclude:
      - 'app/views/**/*'
      - 'app/components/**/*'
