# Note that the local default.yml is overwritten on CodeClimate with the contents of
# the remote rubocop.yml pulled from GitHub in a codeclimate prepare step.
inherit_from:
  - default.yml

#
# Uncomment this section to check specs
# require: rubocop-rspec
#
# RSpec/NamedSubject:
#   Enabled: false
#
# RSpec/ExampleLength:
#   Max: 10
# End rubocop-rspec
#

# RSpec/DescribeClass:
#   Enabled: false
#   Exclude:
#     - "spec/views/**/*"

# Note that inheriting from a gem does not work as CodeClimate cannot cope with this
# inherit_gem:
#   airslie-style:
#     - default.yml

AllCops:
  UseCache: true
  TargetRubyVersion: 2.4
  # Just defining the Exclude or Include keys here overwrites the settings in default.yml
  # so we have to redefine the entire set
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/**/*"
    - "spec/dummy/bin/**/*"
    - "spec/dummy/lib/tasks/**/*"
    - "spec/dummy/db/**/*"
    - "tmp/**/*"
    - "spec/dummy/tmp/**/*"
    - "vendor/bundle/**/*"
    - "config/initializers/devise.rb"

Rails/LexicallyScopedActionFilter:
  Enabled: false
