# rubocop config vases loosely on
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
# but excluding standardrb for now as it removes spaces from hashes which is just plain ugly :)

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Standard's config uses custom cops, so it must be loaded. Skip for now though.
  # - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Skip standard for now.
# inherit_gem:
#   standard: config/base.yml

inherit_from:
  - https://raw.githubusercontent.com/airslie/styleguide/main/rubocop.yml
  - .rubocop_todo.yml
  - .rubocop_strict.yml

AllCops:
  NewCops: disable
  UseCache: true
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  # Defining the Exclude or Include keys here overwrites the settings in styleguide/rubocop.yml
  # so we have to redefine the entire set.
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/**/*"
    - "spec/dummy/bin/**/*"
    - "spec/dummy/lib/tasks/**/*"
    - "spec/dummy/db/**/*"
    - "tmp/**/*"
    - "spec/dummy/tmp/**/*"
    - "vendor/bundle/**/*"
    - "config/initializers/devise.rb"
    - "features/support/env.xaction_view.rb"

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true

RSpec/ReceiveMessages:
  Enabled: true

RSpec/MetadataStyle:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/components/renalware/letters/unread_electronic_ccs_component_spec.rb"

Layout/LineLength:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"
    - "features/step_definitions/**/*"
    - "config/initializers/**/*"
    - "app/inputs/**.*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/dummy/db/migrate/**/*"
    - "db/migrate/**/*"
Metrics/AbcSize:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"
    - "features/**/*"
    - "db/**/*"
  Max: 25
RSpec/ExampleLength:
  Max: 40
  Exclude:
    - "spec/system/**/*"
RSpec/NestedGroups:
  Max: 4
RSpec/MultipleExpectations:
  Max: 6
  Exclude:
    - "spec/system/**/*"
Lint/RedundantSafeNavigation:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
Performance/RedundantBlockCall:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
Rails/DurationArithmetic:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false

# HL7 messages contain strings which seem to be escaped and aren't so its safest to disable this
# cop on all specs
Style/RedundantStringEscape:
  Enabled: true
  Exclude:
    - "spec/**/*"

# This is Ruby >=3.1 so we have to wait for Kings to upgrade
Naming/BlockForwarding:
  Enabled: true

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - "**/*_drop.rb"
