require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Note that the local default.yml is overwritten on CodeClimate with the contents of
# the remote rubocop.yml pulled from GitHub in a codeclimate prepare step.
inherit_from:
  - default.yml

#
# Uncomment this section to check specs
# require: rubocop-rspec
#
# RSpec/NamedSubject:
#   Enabled: false
#
# RSpec/ExampleLength:
#   Max: 10
# End rubocop-rspec
#

# RSpec/DescribeClass:
#   Enabled: false
#   Exclude:
#     - "spec/views/**/*"

# Note that inheriting from a gem does not work as CodeClimate cannot cope with this
# inherit_gem:
#   airslie-style:
#     - default.yml

AllCops:
  UseCache: true
  TargetRubyVersion: 2.5
  # Just defining the Exclude or Include keys here overwrites the settings in default.yml
  # so we have to redefine the entire set
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/**/*"
    - "demo_data/**/*"
    - "spec/dummy/bin/**/*"
    - "spec/dummy/lib/tasks/**/*"
    - "spec/dummy/db/**/*"
    - "tmp/**/*"
    - "spec/dummy/tmp/**/*"
    - "vendor/bundle/**/*"
    - "config/initializers/devise.rb"

Layout/LineLength:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"

Metrics/AbcSize:
  Exclude:
    - "spec/acceptance/renalware/steps/**/*"
    - "db/**/*"
  Max: 21
RSpec/ExampleLength:
  Max: 40
RSpec/NestedGroups:
  Max: 4
RSpec/MultipleExpectations:
  Max: 6
RSpec/DescribeClass:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
Performance/RedundantBlockCall:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
