version: "0.5"

processes:
  web:
    command: |
      bundle check || bundle install
      rails db:migrate
      bin/web -p 3000
    depends_on:
      postgresql:
        condition: process_healthy

  worker:
    command: bin/good_job

  js:
    command: bin/yarn build --watch

  css:
    command: bin/yarn build:css --watch

  # Make this a service you can start manually
  #docs: cd documentation && yarn run start -p 3001
