<?php
//--Fri Mar  8 11:02:26 EST 2013--
$thismodlbl="Transplant Op";

$txop_map=array(
'txop_id'=>'Op ID',
'txopdate'=>'Op Date',
'txopno'=>'Tx Op No',
'txoptype'=>'Op type',
'patage'=>'patient age',
'lastdialdate'=>'Last Dial date',
'donortype'=>'Donor type',
'donorsex'=>'Donor sex',
'donorbirthdate'=>'Donor DOB',
'donorage'=>'Donor age',
'donorweight'=>'Donor weight',
'donor_deathcause'=>'Donor cause of death',
'donorHLA'=>'Donor HLA',
'HLAmismatch'=>'HLA mismatch',
'donorCMVstatus'=>'Donor CMV status',
'recipCMVstatus'=>'Recip CMV status',
'donor_bloodtype'=>'Donor blood type',
'recip_bloodtype'=>'Recip blood type',
'kidneyside'=>'kidney side',
'kidney_asyst'=>'kidney asyst',
'txsite'=>'transplant site',
'kidney_age'=>'kidney age',
'kidney_weight'=>'kidney weight',
'coldinfustime'=>'cold infusion time',
'failureflag'=>'Tx Failed?',
'failuredate'=>'failure date',
'failurecause'=>'failure cause',
'failuredescr'=>'failure descr',
'stentremovaldate'=>'stent removal date',
'graftfxn'=>'graft fxn',
'immunosuppneed'=>'needs immunosuppr',
'dsa_date'=>'DSA test date',
'dsa_result'=>'DSA results',
'dsa_notes'=>'DSA notes',
'bkv_date'=>'BKV test date',
'bkv_result'=>'BKV results',
'bkv_notes'=>'BKV notes',
);

$allfieldlist=array(
    'txop_id',
    'txopdate',
    'txopno',
    'txoptype',
    'patage',
    'lastdialdate',
    'donortype',
    'donorsex',
    'donorbirthdate',
    'donorage',
    'donorweight',
    'donor_deathcause',
    'donorHLA',
    'HLAmismatch',
    'donorCMVstatus',
    'recipCMVstatus',
    'donor_bloodtype',
    'recip_bloodtype',
    'kidneyside',
    'kidney_asyst',
    'txsite',
    'kidney_age',
    'kidney_weight',
    'coldinfustime',
    'failureflag',
    'failuredate',
    'failurecause',
    'failuredescr',
    'stentremovaldate',
    'graftfxn',
    'immunosuppneed',
    'dsa_date',
    'dsa_result',
    'dsa_notes',
    'bkv_date',
    'bkv_result',
    'bkv_notes'
);
