require_relative "ethnicities"
require_relative "religions"
require_relative "languages"
require_relative "marital_statuses"
require_relative "surveys/eq5d_5l"
require_relative "surveys/pos_s"
require_relative "attachment_types"
