require_relative "patients_ethnicities"
require_relative "patients_religions"
require_relative "patients_languages"
require_relative "surveys/eq5d_5l"
require_relative "surveys/pos_s"
require_relative "attachment_types"
