<?php
header("Content-type: text/plain");
include '/Users/lat/projects/renalwarev2/tmp/renalwareconn.php';
include '../../req/confcheckfxns.php';
$fieldslist=$_POST['fieldslist'];
$headerslist=$_POST['headerslist'];
$sql=$_POST['runsql'];
//echo "FIELDS: $fieldslist <br>";
$headersdata=explode(",",$headerslist);
foreach ($headersdata as $key => $value) {
	echo "$value\t";
}
echo "\r\r";
//echo "SQL: $sql";
$mysqli->select_db("renalware");
$result = $mysqli->query($sql);
$numrows=$result->num_rows;
while($row = $result->fetch_assoc())
	{
	foreach ($row as $key => $value) {
//		echo "$value\t";
		echo htmlspecialchars_decode($value, ENT_QUOTES) . "\t";
	}
	echo "\r";
	}
echo "\r\r-----------------------\r";
echo "$numrows rows generated by your Renalware query:\r $sql.";
?>