# These inflection rules are supported but not enabled by default:
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "ACR"
  inflect.acronym "AKCC"
  inflect.acronym "AKI"
  inflect.acronym "APD"
  inflect.acronym "API"
  inflect.acronym "BLT"
  inflect.acronym "BMI"
  inflect.acronym "CAPD"
  inflect.acronym "CC"
  inflect.acronym "CCs"
  inflect.acronym "CM"
  inflect.acronym "CRF"
  inflect.acronym "CSV"
  inflect.acronym "DMD"
  inflect.acronym "DNA"
  inflect.acronym "EDTA"
  inflect.acronym "EQ5D"
  inflect.acronym "EQ5D5L"
  inflect.acronym "ESRF"
  inflect.acronym "FHIR"
  inflect.acronym "GMC"
  inflect.acronym "GP"
  inflect.acronym "HD"
  inflect.acronym "HDF"
  inflect.acronym "HIV"
  inflect.acronym "HL7"
  inflect.acronym "IMD"
  inflect.acronym "ITK"
  inflect.acronym "ITK3"
  inflect.acronym "KFRE"
  inflect.acronym "LAD"
  inflect.acronym "LSOA"
  inflect.acronym "MDM"
  inflect.acronym "MDMs"
  inflect.acronym "MRG"
  inflect.acronym "MS"
  inflect.acronym "MSE"
  inflect.acronym "MSOA"
  inflect.acronym "NHS"
  inflect.acronym "NHSBT"
  inflect.acronym "NK1"
  inflect.acronym "OBX"
  inflect.acronym "ODS"
  inflect.acronym "DSE"
  inflect.acronym "PD"
  inflect.acronym "PET"
  inflect.acronym "PRD"
  inflect.acronym "PV1"
  inflect.acronym "PV2"
  inflect.acronym "QR"
  inflect.acronym "RaDaR"
  inflect.acronym "RTF"
  inflect.acronym "SCH"
  inflect.acronym "SFTP"
  inflect.acronym "TRUD"
  inflect.acronym "UKT"
  inflect.acronym "UKRDC"
  inflect.acronym "VMP"
  inflect.acronym "VND"
  inflect.acronym "XHR"
  inflect.acronym "YAML"

  inflect.uncountable %w(cache stats)
  inflect.irregular "feedback", "feedback"
  # inflect.acronym "POS" # DO NOT USE: breaks Devise/Responders which will translate POST to POS_T!
end
