# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Patient.find_or_create_by!(:nhs_number => "1000124502") do |patient|
  patient.local_patient_id = "Z999999" 
  patient.surname = "RABBIT" 
  patient.forename = "R"
  patient.dob = "01/01/1947"
  patient.paediatric_patient_indicator = "1"
  patient.sex = 1
  patient.ethnicity_id = 1
end

PatientEventType.find_or_create_by!(name: "Access clinic")
PatientEventType.find_or_create_by!(name: "Anaemia clinic")
PatientEventType.find_or_create_by!(name: "CAPD Nurses clinic")
PatientEventType.find_or_create_by!(name: "CAPD clinic")
PatientEventType.find_or_create_by!(name: "Counsellor Meeting")
PatientEventType.find_or_create_by!(name: "Dietitians clinic")
PatientEventType.find_or_create_by!(name: "General Nephrology Clinic")
PatientEventType.find_or_create_by!(name: "Haemodialysis clinic")
PatientEventType.find_or_create_by!(name: "Home Haemodialysis clinic")
PatientEventType.find_or_create_by!(name: "Iron clinic")
PatientEventType.find_or_create_by!(name: "Low Clearance clinic")
PatientEventType.find_or_create_by!(name: "Meeting with family")
PatientEventType.find_or_create_by!(name: "MDM--Liver Renal Virology")
PatientEventType.find_or_create_by!(name: "MDM--Renal Biopsy")
PatientEventType.find_or_create_by!(name: "MDM--Radiology")
PatientEventType.find_or_create_by!(name: "MDM--Renal Sickle")
PatientEventType.find_or_create_by!(name: "Physiotherapist")
PatientEventType.find_or_create_by!(name: "Research visit")
PatientEventType.find_or_create_by!(name: "Result Review")
PatientEventType.find_or_create_by!(name: "Social Worker")
PatientEventType.find_or_create_by!(name: "Telephone call")
PatientEventType.find_or_create_by!(name: "Email")
PatientEventType.find_or_create_by!(name: "Transplant clinic")
PatientEventType.find_or_create_by!(name: "Walk-in clinic")
PatientEventType.find_or_create_by!(name: "Ward round")
PatientEventType.find_or_create_by!(name: "Dartford Outreach Clinic")
PatientEventType.find_or_create_by!(name: "Woolwich Outreach Clinic")
PatientEventType.find_or_create_by!(name: "Plasma Exchange")
PatientEventType.find_or_create_by!(name: "Tx Coordination")

Ethnicity.find_or_create_by!(name: "White")
Ethnicity.find_or_create_by!(name: "Black Caribbean")
Ethnicity.find_or_create_by!(name: "Black African")
Ethnicity.find_or_create_by!(name: "Black/other/non-mixed origin")
Ethnicity.find_or_create_by!(name: "Indian")
Ethnicity.find_or_create_by!(name: "Pakistani")
Ethnicity.find_or_create_by!(name: "Bangladeshi")
Ethnicity.find_or_create_by!(name: "Chinese")
Ethnicity.find_or_create_by!(name: "Black British")
Ethnicity.find_or_create_by!(name: "Black Caribbean")
Ethnicity.find_or_create_by!(name: "Black North African")
Ethnicity.find_or_create_by!(name: "Black--other African country")
Ethnicity.find_or_create_by!(name: "Black East African Asian")
Ethnicity.find_or_create_by!(name: "Black Indian sub-continent")
Ethnicity.find_or_create_by!(name: "Black--other Asian")
Ethnicity.find_or_create_by!(name: "Black Black - other")
Ethnicity.find_or_create_by!(name: "Black--other/mixed")
Ethnicity.find_or_create_by!(name: "Other Black--Black/White origin")
Ethnicity.find_or_create_by!(name: "Other Black--Black/Asian origin")
Ethnicity.find_or_create_by!(name: "Other ethnic non-mixed (NMO)")
Ethnicity.find_or_create_by!(name: "British ethnic minority spec.(NMO)")
Ethnicity.find_or_create_by!(name: "British ethnic minority unsp (NMO)")
Ethnicity.find_or_create_by!(name: "Caribbean Island (NMO)")
Ethnicity.find_or_create_by!(name: "North African Arab (NMO)")
Ethnicity.find_or_create_by!(name: "Other African countries (NMO)")
Ethnicity.find_or_create_by!(name: "East African Asian (NMO)")
Ethnicity.find_or_create_by!(name: "Indian sub-continent (NMO)")
Ethnicity.find_or_create_by!(name: "Other Asian (NMO)")
Ethnicity.find_or_create_by!(name: "Irish (NMO)")
Ethnicity.find_or_create_by!(name: "Greek Cypriot (NMO)")
Ethnicity.find_or_create_by!(name: "Turkish Cypriot (NMO)")
Ethnicity.find_or_create_by!(name: "Other European (NMO)")
Ethnicity.find_or_create_by!(name: "Other ethnic NEC (NMO)")
Ethnicity.find_or_create_by!(name: "Other ethnic/mixed origin")
Ethnicity.find_or_create_by!(name: "Other ethnic/Black/White origin")
Ethnicity.find_or_create_by!(name: "Other ethnic/Asian/White origin")
Ethnicity.find_or_create_by!(name: "Other ethnic/mixed white origin")
Ethnicity.find_or_create_by!(name: "Other ethnic/other mixed origin")
Ethnicity.find_or_create_by!(name: "Refused")

ModalityCode.find_or_create_by!(name: "None")
ModalityCode.find_or_create_by!(name: "CAPD (disconnect)")
ModalityCode.find_or_create_by!(name: "CAPD (standard)") 
ModalityCode.find_or_create_by!(name: "CCPD (<6 nights/wk)") 
ModalityCode.find_or_create_by!(name: "CCPD (6/7 nights/wk)")
ModalityCode.find_or_create_by!(name: "Haemodialysis")
ModalityCode.find_or_create_by!(name: "Haemofiltration")
ModalityCode.find_or_create_by!(name: "Haemodiafiltration") 
ModalityCode.find_or_create_by!(name: "Ultrafiltration") 
ModalityCode.find_or_create_by!(name: "Transplant (cad - HB)")
ModalityCode.find_or_create_by!(name: "Transplant (cad - NHB)") 
ModalityCode.find_or_create_by!(name: "Transplant (LRD)")
ModalityCode.find_or_create_by!(name: "Transplant (LUD)")
ModalityCode.find_or_create_by!(name: "Conservative care")
ModalityCode.find_or_create_by!(name: "Recovery of renal function")
ModalityCode.find_or_create_by!(code: "death", name: "Death")

PdToHaemodialysis.find_or_create_by!(rr_code: 201, description: "Patient / partner choice") 
PdToHaemodialysis.find_or_create_by!(rr_code: 202, description: "Loss of supporting partner") 
PdToHaemodialysis.find_or_create_by!(rr_code: 203, description: "Other change of personal circumstances")
PdToHaemodialysis.find_or_create_by!(rr_code: 204, description: "Inability to perform PD")
PdToHaemodialysis.find_or_create_by!(rr_code: 205, description: "Other reasons")
PdToHaemodialysis.find_or_create_by!(rr_code: 211, description: "Frequent / Recurrent peritonitis with or without loss of UF")
PdToHaemodialysis.find_or_create_by!(rr_code: 212, description: "Unresolving peritonitis")
PdToHaemodialysis.find_or_create_by!(rr_code: 213, description: "Catheter loss through exit site infection")
PdToHaemodialysis.find_or_create_by!(rr_code: 214, description: "Loss of UF")
PdToHaemodialysis.find_or_create_by!(rr_code: 215, description: "Inadequate clearance")
PdToHaemodialysis.find_or_create_by!(rr_code: 216, description: "Abdominal surgery or complications")

HaemodialysisToPd.find_or_create_by!(rr_code: 221, description: "Patient / partner choice")
HaemodialysisToPd.find_or_create_by!(rr_code: 222, description: "Loss of supporting partner")
HaemodialysisToPd.find_or_create_by!(rr_code: 223, description: "Other change of personal circumstances")
HaemodialysisToPd.find_or_create_by!(rr_code: 224, description: "Lack of HD facilities")
HaemodialysisToPd.find_or_create_by!(rr_code: 225, description: "Other reasons")
HaemodialysisToPd.find_or_create_by!(rr_code: 231, description: "Loss of vascular access")
HaemodialysisToPd.find_or_create_by!(rr_code: 232, description: "Haemodynamic instability")
HaemodialysisToPd.find_or_create_by!(rr_code: 233, description: "Elective after temporary HD")

EdtaCode.find_or_create_by!(code: 0, death_cause: "Cause of death uncertain/not determined [0]")       
EdtaCode.find_or_create_by!(code: 11, death_cause: "Myocardial ischaemia and infarction [11]")
EdtaCode.find_or_create_by!(code: 12, death_cause: "Hyperkalaemia [12]")
EdtaCode.find_or_create_by!(code: 13, death_cause: "Haemorrhagic pericarditis [13]")
EdtaCode.find_or_create_by!(code: 14, death_cause: "Other causes of cardiac failure [14]")
EdtaCode.find_or_create_by!(code: 15, death_cause: "Cardiac arrest/sudden death; other cause or unknown [15]")
EdtaCode.find_or_create_by!(code: 16, death_cause: "Hypertensive cardiac failure [16]")
EdtaCode.find_or_create_by!(code: 17, death_cause: "Hypokalaemia [17]")
EdtaCode.find_or_create_by!(code: 18, death_cause: "Fluid overload/pulmonary oedema [18]")
EdtaCode.find_or_create_by!(code: 21, death_cause: "Pulmonary embolus [21]")
EdtaCode.find_or_create_by!(code: 22, death_cause: "Cerebro-vascular accident, other cause or unspecified [22]")
EdtaCode.find_or_create_by!(code: 23, death_cause: "Gastro-intestinal haemorrhage (digestive) [23]")
EdtaCode.find_or_create_by!(code: 24, death_cause: "Haemorrhage from graft site [24]")
EdtaCode.find_or_create_by!(code: 25, death_cause: "Hameorrhage from vascular access or dialysis circuit [25]")
EdtaCode.find_or_create_by!(code: 26, death_cause: "Haemorrhage from ruptured vascular aneurysm (not code 22 or 23) [26]")
EdtaCode.find_or_create_by!(code: 27, death_cause: "Haemorrhage from surgery (not codes 23,24,26) [27]")
EdtaCode.find_or_create_by!(code: 28, death_cause: "Other haemorrhage, (not codes 23-27) [28]")
EdtaCode.find_or_create_by!(code: 29, death_cause: "Mesenteric infarction [29]")
EdtaCode.find_or_create_by!(code: 31, death_cause: "Pulmonary infection bacterial (not code 73) [31]")
EdtaCode.find_or_create_by!(code: 32, death_cause: "Pulmonary infection (viral) [32]")
EdtaCode.find_or_create_by!(code: 33, death_cause: "Pulmonary infection (fungal or protozoal; parasitic) [33]")
EdtaCode.find_or_create_by!(code: 34, death_cause: "Infections elsewhere except viral hepatitis [34]")
EdtaCode.find_or_create_by!(code: 35, death_cause: "Septicaemia [35]")
EdtaCode.find_or_create_by!(code: 36, death_cause: "Tuberculosis (lung) [36]")
EdtaCode.find_or_create_by!(code: 37, death_cause: "Tuberculosis (elsewhere) [37]")
EdtaCode.find_or_create_by!(code: 38, death_cause: "Generalized viral infection [38]")
EdtaCode.find_or_create_by!(code: 39, death_cause: "Peritonitis (all causes except for Peritoneal Dialysis) [39]")
EdtaCode.find_or_create_by!(code: 41, death_cause: "Liver disease due to hepatitis B virus [41]")
EdtaCode.find_or_create_by!(code: 42, death_cause: "Liver disease due to other viral hepatitis [42]")
EdtaCode.find_or_create_by!(code: 43, death_cause: "Liver disease due to drug toxicity [43]")
EdtaCode.find_or_create_by!(code: 44, death_cause: "Cirrhosis - not viral (alcoholic or other cause) [44]")
EdtaCode.find_or_create_by!(code: 45, death_cause: "Cystic liver disease [45]")
EdtaCode.find_or_create_by!(code: 46, death_cause: "Liver failure - cause unknown [46]")
EdtaCode.find_or_create_by!(code: 51, death_cause: "Patient refused further treatment for ESRF [51]")
EdtaCode.find_or_create_by!(code: 52, death_cause: "Suicide [52]")
EdtaCode.find_or_create_by!(code: 53, death_cause: "ESRF treatment ceased for any other reason [53]")
EdtaCode.find_or_create_by!(code: 54, death_cause: "ESRF treatment withdrawn for medical reasons [54]")
EdtaCode.find_or_create_by!(code: 61, death_cause: "Uraemia caused by graft failure [61]")
EdtaCode.find_or_create_by!(code: 62, death_cause: "Pancreatitis [62]")
EdtaCode.find_or_create_by!(code: 63, death_cause: "Bone marrow depression (Aplasia) [63]")
EdtaCode.find_or_create_by!(code: 64, death_cause: "Cachexia [64]")
EdtaCode.find_or_create_by!(code: 66, death_cause: "Malignant disease in patient treated by immunosuppressive therapy [66]")
EdtaCode.find_or_create_by!(code: 67, death_cause: "Malignant disease: solid tumors except those of 66 [67]")
EdtaCode.find_or_create_by!(code: 68, death_cause: "Malignant disease: lymphoproliferative disorders (Except 66) [68]")
EdtaCode.find_or_create_by!(code: 69, death_cause: "Dementia [69]")
EdtaCode.find_or_create_by!(code: 70, death_cause: "Peritonitis (sclerosing, with peritoneal dialysis) [70]")
EdtaCode.find_or_create_by!(code: 71, death_cause: "Perforation of peptic ulcer [71]")
EdtaCode.find_or_create_by!(code: 72, death_cause: "Perforation of colon [72]")
EdtaCode.find_or_create_by!(code: 73, death_cause: "Chronic obstructive pulmonary disease [73]")
EdtaCode.find_or_create_by!(code: 81, death_cause: "Accident related to ESRF treatment (not 25) [81]")
EdtaCode.find_or_create_by!(code: 82, death_cause: "Accident unrelated to ESRF treatment [82]")
EdtaCode.find_or_create_by!(code: 99, death_cause: "Other identified cause of death [99]")
EdtaCode.find_or_create_by!(code: 100, death_cause: "0Peritonitis (bacterial, with peritoneal dialysis) [100]")
EdtaCode.find_or_create_by!(code: 101, death_cause: "1Peritonitis (fungal, with peritoneal dialysis) [101]")
EdtaCode.find_or_create_by!(code: 102, death_cause: "2Peritonitis (due to other cause, with peritoneal dialysis) [102]")
