# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

p "Loading Dummy rake tasks"

# If we are running on Heroku this Rakefile is loaded _before_ the engine's rakefile so
# APP_RAKEFILE is undefined, and we must point it at this file as this constant is used in railties
unless defined?(APP_RAKEFILE)
  p "Defining APP_RAKEFILE in the dummy app"
  APP_RAKEFILE = __FILE__
end

require_relative "config/application"

p "Resolved APP_RAKEFILE to #{APP_RAKEFILE}"
Rails.application.load_tasks
