# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

puts "Loading spec/dummy rake tasks"

# If we are running on Heroku this Rakefile is loaded _before_ the engine's rakefile so
# APP_RAKEFILE is undefined, and we must point it at this file as this constant is used in railties
unless defined?(APP_RAKEFILE)
  APP_RAKEFILE = __FILE__
end

require_relative "config/application"

Rails.application.load_tasks
