require_relative "registration_statuses"
require_relative "failure_cause_descriptions"
require_relative "donor_stages"
require_relative "rejection_treatments"
require_relative "investigation_types"
require_relative "induction_agents"
