default: &default
  adapter: postgresql
  encoding: unicode
  # See comments re schema_search_path in 20171116103230_move_objects_to_renalware_schema.rb
  schema_search_path: "renalware,renalware_demo,public,heroku_ext"
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

default_credentials: &default_credentials
  username: <%= ENV["POSTGRES_USER"] || "renalware" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "renalware" %>

development:
  <<: *default
  <<: *default_credentials

  # To use another database, pass MYDB=xxx as an argument, e.g. MYDB=xxx bin/web
  database: <%= ENV.fetch("MYDB", "renalware_development") %>

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  min_messages: notice

test:
  <<: *default
  <<: *default_credentials
  database: renalware_test
  pool: 100

# Used by renalware-demo Heroku site
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
