CREATE TABLE `sharedcaredata` (
  `sharedcare_id` mediumint(7) unsigned NOT NULL AUTO_INCREMENT,
  `sharedcarestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sharedcareuid` smallint(4) unsigned DEFAULT NULL,
  `sharedcareuser` varchar(20) DEFAULT NULL,
  `sharedcarezid` mediumint(8) unsigned DEFAULT NULL,
  `sharedcareadddate` date DEFAULT NULL,
  `sharedcaredate` date DEFAULT NULL,
  `currentflag` tinyint(1) unsigned DEFAULT '1',
  `q1interest` char(1) DEFAULT NULL,
  `q1participating` tinyint(1) unsigned DEFAULT '0',
  `q1completed` tinyint(1) DEFAULT '0',
  `q1completed_by` varchar(20) DEFAULT NULL,
  `q1completed_date` date DEFAULT NULL,
  `q2interest` char(1) DEFAULT NULL,
  `q2participating` tinyint(1) unsigned DEFAULT '0',
  `q2completed` tinyint(1) DEFAULT '0',
  `q2completed_by` varchar(20) DEFAULT NULL,
  `q2completed_date` date DEFAULT NULL,
  `q3interest` char(1) DEFAULT NULL,
  `q3participating` tinyint(1) unsigned DEFAULT '0',
  `q3completed` tinyint(1) DEFAULT '0',
  `q3completed_by` varchar(20) DEFAULT NULL,
  `q3completed_date` date DEFAULT NULL,
  `q4interest` char(1) DEFAULT NULL,
  `q4participating` tinyint(1) unsigned DEFAULT '0',
  `q4completed` tinyint(1) DEFAULT '0',
  `q4completed_by` varchar(20) DEFAULT NULL,
  `q4completed_date` date DEFAULT NULL,
  `q5interest` char(1) DEFAULT NULL,
  `q5participating` tinyint(1) unsigned DEFAULT '0',
  `q5completed` tinyint(1) DEFAULT '0',
  `q5completed_by` varchar(20) DEFAULT NULL,
  `q5completed_date` date DEFAULT NULL,
  `q6interest` char(1) DEFAULT NULL,
  `q6participating` tinyint(1) unsigned DEFAULT '0',
  `q6completed` tinyint(1) DEFAULT '0',
  `q6completed_by` varchar(20) DEFAULT NULL,
  `q6completed_date` date DEFAULT NULL,
  `q7interest` char(1) DEFAULT NULL,
  `q7participating` tinyint(1) unsigned DEFAULT '0',
  `q7completed` tinyint(1) DEFAULT '0',
  `q7completed_by` varchar(20) DEFAULT NULL,
  `q7completed_date` date DEFAULT NULL,
  `q8interest` char(1) DEFAULT NULL,
  `q8participating` tinyint(1) unsigned DEFAULT '0',
  `q8completed` tinyint(1) DEFAULT '0',
  `q8completed_by` varchar(20) DEFAULT NULL,
  `q8completed_date` date DEFAULT NULL,
  `q9interest` char(1) DEFAULT NULL,
  `q9participating` tinyint(1) unsigned DEFAULT '0',
  `q9completed` tinyint(1) DEFAULT '0',
  `q9completed_by` varchar(20) DEFAULT NULL,
  `q9completed_date` date DEFAULT NULL,
  `q10interest` char(1) DEFAULT NULL,
  `q10participating` tinyint(1) unsigned DEFAULT '0',
  `q10completed` tinyint(1) DEFAULT '0',
  `q10completed_by` varchar(20) DEFAULT NULL,
  `q10completed_date` date DEFAULT NULL,
  `q11interest` char(1) DEFAULT NULL,
  `q11participating` tinyint(1) unsigned DEFAULT '0',
  `q11completed` tinyint(1) DEFAULT '0',
  `q11completed_by` varchar(20) DEFAULT NULL,
  `q11completed_date` date DEFAULT NULL,
  `q12interest` char(1) DEFAULT NULL,
  `q12participating` tinyint(1) unsigned DEFAULT '0',
  `q12completed` tinyint(1) DEFAULT '0',
  `q12completed_by` varchar(20) DEFAULT NULL,
  `q12completed_date` date DEFAULT NULL,
  `q13interest` char(1) DEFAULT NULL,
  `q13participating` tinyint(1) unsigned DEFAULT '0',
  `q13completed` tinyint(1) DEFAULT '0',
  `q13completed_by` varchar(20) DEFAULT NULL,
  `q13completed_date` date DEFAULT NULL,
  `q14interest` char(1) DEFAULT NULL,
  `q14participating` tinyint(1) unsigned DEFAULT '0',
  `q14completed` tinyint(1) DEFAULT '0',
  `q14completed_by` varchar(20) DEFAULT NULL,
  `q14completed_date` date DEFAULT NULL,
  PRIMARY KEY (`sharedcare_id`),
  KEY `sharedcarezid` (`sharedcarezid`),
  KEY `sharedcareuid` (`sharedcareuid`),
  KEY `sharedcareadddate` (`sharedcareadddate`),
  KEY `sharedcaredate` (`sharedcaredate`),
  KEY `currentflag` (`currentflag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;