module Renalware
  module Medications
    module Delivery
      describe PurchaseOrderNumber do
        describe "#next_number" do
          it "returns the next number generated by a postgres sequence" do
            number = described_class.next_number

            expect(number).to be_a(Integer)
            expect(described_class.next_number).to eq(number + 1)
          end
        end

        describe "#next" do
          it "returns the a formatted number" do
            allow(described_class).to receive(:next_number).and_return(100)
            allow(Renalware.config)
              .to receive(:medication_delivery_purchase_order_prefix).and_return("X")

            expect(described_class.next).to eq("X100")
          end
        end
      end
    end
  end
end
