<?php
//----Mon 13 Jan 2014----updated codes
$pathfieldoptions='<option value="ACRA">ACRA--Urine Albumin/Creat Ratio</option>
<option value="AFP">AFP--AFP</option>
<option value="AL">AL--Serum Aluminium</option>
<option value="ALB">ALB--Albumin</option>
<option value="ALP">ALP--Alkaline Phosphatase (ALP)</option>
<option value="ALT">ALT--Alanine Aminotransferase (ALT)</option>
<option value="AMY">AMY--Amylase</option>
<option value="ANA">ANA--Anti Nuclear antibodies</option>
<option value="ANCA">ANCA--Anti Neutrophil Cyto Ab</option>
<option value="APTH">APTH--APTR (Heparin)</option>
<option value="APTR">APTR--APTR</option>
<option value="ASM">ASM--Anti Smooth Muscle antibodies</option>
<option value="AST">AST--AST</option>
<option value="B12">B12--Vitamin B12</option>
<option value="BGLU">BGLU--Blood Glucose</option>
<option value="BHBC">BHBC--Hepatitis B core total Ab</option>
<option value="BHBS">BHBS--Hepatitis B surface antibody</option>
<option value="BHCV">BHCV--Hepatitis C virus antibody</option>
<option value="BIC">BIC--Bicarbonate</option>
<option value="BIL">BIL--Total Bilirubin</option>
<option value="C125">C125--CA125</option>
<option value="C199">C199--CA199</option>
<option value="C3">C3--Complement (C3)</option>
<option value="C4">C4--Complement (C4)</option>
<option value="CAER">CAER--Caeruloplasmin</option>
<option value="CAL">CAL--Calcium</option>
<option value="CCA">CCA--Corrected Calc</option>
<option value="CEA">CEA--CEA</option>
<option value="CHOL">CHOL--Cholesterol</option>
<option value="CK">CK--CK</option>
<option value="CRCL">CRCL--Creat Clearance</option>
<option value="CRE">CRE--Creatinine</option>
<option value="CRP">CRP--C-Reactive Protein</option>
<option value="CRYO">CRYO--Cryoglobulins</option>
<option value="CU">CU--Serum Copper</option>
<option value="CYA">CYA--Cyclosporin A</option>
<option value="DNA">DNA--Anti dsDNA antibodies</option>
<option value="ESRR">ESRR--ESR</option>
<option value="FER">FER--Ferritin</option>
<option value="FIB">FIB--Fibrinogen</option>
<option value="FOL">FOL--Folate</option>
<option value="GGT">GGT--Gamma GT</option>
<option value="GLO">GLO--Globulin</option>
<option value="HB">HB--Haemoglobin (NOTE: not HGB)</option>
<option value="HBA">HBA--HbA1c (DCCT)</option>
<option value="HBAI">HBAI--HbA1c (IFCC)</option>
<option value="HCVGI">HCVGI--HCVGI</option>
<option value="HDL">HDL--Hdl Chol</option>
<option value="HYPO">HYPO--% HYPO</option>
<option value="IGLA">IGLA--IGA</option>
<option value="IGLG">IGLG--IGG</option>
<option value="IGLM">IGLM--IGM</option>
<option value="INR">INR--INR</option>
<option value="LDL">LDL--Ldl Chol</option>
<option value="LKM">LKM--Liver Kidney Microsomal Abs</option>
<option value="LYM">LYM--Lymphocyte Count</option>
<option value="MCH">MCH--MCH</option>
<option value="MCV">MCV--MCV</option>
<option value="MDRD">MDRD--MDRD internal result/1.73m2</option>
<option value="MG">MG--Magnesium</option>
<option value="MITO">MITO--Anti Mitochondrial antibodies</option>
<option value="NA">NA--Sodium</option>
<option value="NEUT">NEUT--Neutrophil Count</option>
<option value="PCRA">PCRA--Urine Protein/Creat Ratio</option>
<option value="PHOS">PHOS--Phosphate</option>
<option value="PLT">PLT--Platelets</option>
<option value="POT">POT--Potassium</option>
<option value="PTHI">PTHI--Parathyroid Hormone</option>
<option value="RETA">RETA--Absolute Reticulocyte Count</option>
<option value="RF">RF--Rheumatoid Factor</option>
<option value="TP">TP--Total Protein</option>
<option value="TRIG">TRIG--Triglycerides</option>
<option value="TSH">TSH--TSH</option>
<option value="UALB">UALB--Urine Albumin conc.</option>
<option value="UPRE">UPRE--Urine Tot. Protein excr.</option>
<option value="UPRO">UPRO--Urine protein</option>
<option value="URAT">URAT--Urate</option>
<option value="URE">URE--Urea</option>
<option value="UREP">UREP--Urea (post dialysis)</option>
<option value="URR">URR--Urea Reduction Ratio</option>
<option value="WBC">WBC--WBC</option>';